name: Cleanup Old Workflow Runs

on:
  schedule:
    - cron: '0 0 * * 0' # Se ejecuta semanalmente los domingos a las 00:00 UTC
  workflow_dispatch: # Permite ejecutarlo manualmente desde la interfaz de GitHub

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Set up GitHub CLI
        run: |
          sudo apt-get install -y gh jq

      - name: Authenticate GitHub CLI
        run: |
          echo "${{ secrets.TOKEN_CLEAN }}" | gh auth login --with-token

      - name: Delete old workflow runs
        env:
          DAYS_TO_KEEP: 30 # Cambia el número de días según sea necesario
          PER_PAGE: 100    # Número de ejecuciones por página
          MAX_DELETIONS: 50 # Número máximo de ejecuciones a eliminar por ciclo
        run: |
          # Obtener la fecha de límite en formato ISO 8601
          DELETE_BEFORE_DATE=$(date -d "$DAYS_TO_KEEP days ago" --utc +%Y-%m-%dT%H:%M:%SZ)
          
          # Contador de eliminaciones
          DELETED_COUNT=0

          # Iterar sobre todas las páginas de ejecuciones completadas
          for (( PAGE=1; ; PAGE++ )); do
            # Obtener lista de ejecuciones completadas y antiguas
            RUNS=$(gh run list --limit $PER_PAGE --json databaseId,createdAt,status \
                  --status completed --page $PAGE \
                  | jq -r --arg DATE "$DELETE_BEFORE_DATE" '.[] | select(.createdAt < $DATE) | .databaseId')

            # Si no hay más ejecuciones, salir del bucle
            if [ -z "$RUNS" ]; then
              echo "No more old workflow runs to delete."
              break
            fi

            # Eliminar cada ejecución y actualizar contador
            for run_id in $RUNS; do
              echo "Deleting workflow run with ID: $run_id"
              gh run delete "$run_id" -y
              DELETED_COUNT=$((DELETED_COUNT+1))
              
              # Esperar un segundo entre eliminaciones para no sobrecargar la API
              sleep 1

              # Si alcanzamos el número máximo de eliminaciones, salir del bucle
              if [ $DELETED_COUNT -ge $MAX_DELETIONS ]; then
                echo "Reached maximum deletions for this run: $MAX_DELETIONS"
                break 2
              fi
            done
          done

          echo "Total workflow runs deleted: $DELETED_COUNT"
