name: Cleanup Old Workflows

on:
  schedule:
    - cron: '0 0 * * 0' # Se ejecuta semanalmente los domingos a las 00:00 UTC
  workflow_dispatch: # Permite ejecutar el workflow manualmente desde la interfaz de GitHub

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up GitHub CLI
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install GitHub CLI
        run: sudo apt-get install gh

      - name: Authenticate GitHub CLI
        run: gh auth login --with-token < ${{ secrets.GITHUB_TOKEN }}

      - name: Delete old workflow runs
        run: |
          # Definir el límite de antigüedad en días (por ejemplo, 30 días)
          DAYS_TO_KEEP=30

          # Obtener la fecha de límite en formato ISO 8601
          DELETE_BEFORE_DATE=$(date -d "$DAYS_TO_KEEP days ago" --utc +%Y-%m-%dT%H:%M:%SZ)

          # Listar todas las ejecuciones y eliminar las que sean anteriores a la fecha límite
          gh run list --limit 100 --json databaseId,createdAt,status \
            | jq -r --arg DATE "$DELETE_BEFORE_DATE" '.[] | select(.status == "completed") | select(.createdAt < $DATE) | .databaseId' \
            | while read run_id; do
                echo "Deleting workflow run with ID: $run_id"
                gh run delete $run_id -y
              done
